CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    OAUTH_ID VARCHAR(128) DEFAULT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(100) DEFAULT NULL,
    USER_NAME VARCHAR(255) DEFAULT NULL
    APP_SESSION_KEY VARCHAR(255) DEFAULT NULL
    
);

CREATE TABLE SERVERS (
    SERVER_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USER_ID INT NOT NULL,
    SERVER_IP VARCHAR(40),
    SERVER_COUNTRY VARCHAR(3),
    SERVER_NAME VARCHAR(32),
    SERVER_USERNAME VARCHAR(32),
    SERVER_PASSWORD VARCHAR(255),
   SERVER_STATUS ENUM('offline', 'online', 'maintenance', 'error') NOT NULL DEFAULT 'maintenance',
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);


CREATE TABLE SERVER_CLIENTS (
    CLIENT_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    SERVER_ID INT NOT NULL,
    CLIENT_NAME VARCHAR(255),
    IS_USED BOOLEAN DEFAULT 0,
    FOREIGN KEY (SERVER_ID) REFERENCES SERVERS(SERVER_ID) ON DELETE CASCADE
);